import SwiftUI
import AppKit

struct TranscriptIntelligenceTab: View {
    @AppStorage("lastTranscriptFolder") private var projectFolder = ""
    @AppStorage("selectedModel") private var selectedModel = OMLXClient.defaultModel
    @AppStorage("timelineFPS") private var timelineFPS: Double = 25.0
    @AppStorage("projectThemesJSON") private var projectThemesJSON = "[]"
    @AppStorage("transcriptIntelligenceFolders") private var ownFoldersJSON = "[]"
    @ObservedObject var subStore: SubtitleStore
    @ObservedObject var docStore: DocumentStore
    @EnvironmentObject var assistantStore: AssistantStore
    @EnvironmentObject var knowledgeStore: KnowledgeStore

    init(subStore: SubtitleStore, docStore: DocumentStore) {
        self.subStore = subStore
        self.docStore = docStore
    }

    @State private var input = ""
    @State private var showClearAlert = false
    @State private var showChatClearAlert = false
    @State private var copiedID: UUID?
    @State private var isGeneratingTitle = false
    @State private var materialTrees: [MaterialNode] = []
    @State private var materialsExpanded = false
    @FocusState private var focused: Bool

    var ownFolders: [String] {
        (try? JSONDecoder().decode([String].self, from: ownFoldersJSON.data(using: .utf8) ?? Data())) ?? []
    }

    var body: some View {
        VStack(spacing: 0) {
            Divider()

            projectBar

            Divider()

            if ownFolders.isEmpty {
                chooseProjectPrompt
            } else if docStore.isLoading || subStore.isLoading {
                loadingState
            } else {
                VStack(spacing: 12) {
                    if assistantStore.messages.isEmpty {
                        readyState
                    } else {
                        chatList
                    }
                    inputBar
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 12)
            }
        }
        .onAppear { loadOwnFolders() }
        .onChange(of: ownFoldersJSON) { _ in loadOwnFolders() }
        .onChange(of: docStore.isLoaded) { _ in buildKnowledge() }
        .onChange(of: subStore.isLoaded) { _ in buildKnowledge() }
        .onChange(of: subStore.isTranscriptsLoaded) { _ in buildKnowledge() }
        .onChange(of: subStore.transcriptEntries.count) { _ in buildKnowledge() }
        .confirmationDialog("Clear conversation?", isPresented: $showChatClearAlert, titleVisibility: .visible) {
            Button("Save as HTML…") { saveConversation(thenClear: true) }
            Button("Clear without saving", role: .destructive) { assistantStore.clear() }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("Save the conversation as HTML before clearing?")
        }
    }

    var projectBar: some View {
        ProjectBar(
            folders: ownFolders,
            emptyPrompt: "Choose project folder…",
            onAdd: { addFolder() },
            onRemove: { p in
                if let idx = ownFolders.firstIndex(of: p) { removeFolder(at: idx) }
            },
            onRescan: { rescanFolder() },
            onClear: { showClearAlert = true },
            trees: materialTrees,
            materialsExpanded: $materialsExpanded
        ) {
            HStack(spacing: 10) {
                if knowledgeStore.isBuilt {
                    Text("\(knowledgeStore.interviews.count) interview(s)")
                        .scaledFont(.caption2)
                        .foregroundColor(.secondary)
                }
                Spacer()
                if !assistantStore.messages.isEmpty {
                    Button {
                        saveConversation()
                    } label: {
                        if isGeneratingTitle {
                            ProgressView().controlSize(.mini)
                        } else {
                            Label("Save", systemImage: "square.and.arrow.down")
                        }
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.mini)
                    .help("Save conversation as HTML — title generated by LLM")
                    .disabled(isGeneratingTitle || assistantStore.isProcessing)

                    Button("Clear") { showChatClearAlert = true }
                        .buttonStyle(.bordered)
                        .controlSize(.mini)
                        .help("Clear conversation")
                        .disabled(isGeneratingTitle)
                }
            }
        }
        .confirmationDialog(
            "Remove all project folders and clear the knowledge base?",
            isPresented: $showClearAlert,
            titleVisibility: .visible
        ) {
            Button("Clear All", role: .destructive) {
                saveOwnFolders([])
                subStore.clearAll()
                docStore.reloadFolders([])
            }
            Button("Cancel", role: .cancel) {}
        }
    }

    var chooseProjectPrompt: some View {
        EmptyStateView(
            icon: "folder.badge.questionmark",
            title: "No project folder selected",
            message: "Choose a folder containing transcripts and\ninterview data to build a searchable knowledge base"
        )
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    var loadingState: some View {
        LoadingPage(title: "Loading project…")
    }

    var readyState: some View {
        VStack(spacing: 16) {
            Spacer()
            Image(systemName: "brain.head.profile")
                .scaledFontSize(40)
                .foregroundColor(.secondary.opacity(0.4))
            Text(knowledgeStore.isBuilt
                ? "Ask about the interviews"
                : "Building knowledge base…")
                .scaledFont(.title3)
                .foregroundColor(.secondary)
            if knowledgeStore.isBuilt {
                Text("\(knowledgeStore.interviews.count) interviews · powered by \(selectedModel)")
                    .scaledFont(.subheadline)
                    .foregroundColor(.secondary)
                    .multilineTextAlignment(.center)
            } else {
                Activity()
            }
            Spacer()
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    var chatList: some View {
        GeometryReader { geo in
            ScrollViewReader { proxy in
                ScrollView {
                    LazyVStack(spacing: 14) {
                        // Top spacer pushes few messages to the bottom (opencode-style bottom-anchored flow)
                        Spacer(minLength: 0)
                        ForEach(assistantStore.messages) { msg in
                            messageBubble(msg)
                                .id(msg.id)
                        }
                    }
                    .frame(minHeight: geo.size.height, alignment: .bottom)
                    .frame(maxWidth: 720)
                    .frame(maxWidth: .infinity)
                    .padding(.horizontal, 16)
                    .padding(.top, 16)
                    .padding(.bottom, 20)
                }
                .onChange(of: assistantStore.messages.count) { _ in
                    if let last = assistantStore.messages.last {
                        withAnimation(.easeOut(duration: 0.25)) { proxy.scrollTo(last.id, anchor: .bottom) }
                    }
                }
                .onChange(of: assistantStore.messages.last?.content) { _ in
                    if let last = assistantStore.messages.last {
                        proxy.scrollTo(last.id, anchor: .bottom)
                    }
                }
            }
        }
    }

    @ViewBuilder
    func messageBubble(_ msg: ChatMessage) -> some View {
        let isUser = msg.role == "user"
        HStack(alignment: .top, spacing: 10) {
            if isUser { Spacer(minLength: 48) }
            Image(systemName: isUser ? "person.fill" : "sparkles")
                .scaledFont(.caption2)
                .foregroundColor(isUser ? .white : .accentColor)
                .frame(width: 26, height: 26)
                .background(isUser ? Color.accentColor : Color.accentColor.opacity(0.14))
                .clipShape(Circle())
                .overlay(Circle().stroke(Color.primary.opacity(0.06), lineWidth: 1))
                .padding(.top, 2)
                .opacity(isUser ? 1 : 0.9)

            VStack(alignment: .leading, spacing: 4) {
                Text(isUser ? "You" : "Assistant")
                    .scaledFont(.caption)
                    .fontWeight(.semibold)
                    .foregroundColor(.secondary)
                Text(msg.content.isEmpty ? (msg.isStreaming ? "…" : "") : msg.content)
                    .scaledFontSize(15)
                    .lineSpacing(2)
                    .textSelection(.enabled)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 10)
                    .background(
                        RoundedRectangle(cornerRadius: UIDesign.cornerCard, style: .continuous)
                            .fill(isUser ? Color.accentColor.opacity(0.14) : Color(nsColor: .controlBackgroundColor))
                    )
                    .overlay(
                        RoundedRectangle(cornerRadius: UIDesign.cornerCard, style: .continuous)
                            .stroke(Color.primary.opacity(isUser ? 0 : 0.06), lineWidth: 1)
                    )
                // Inline actions — opencode-style subtle row
                HStack(spacing: 8) {
                    if isUser {
                        Button {
                            if let text = assistantStore.revertUserMessage(id: msg.id) {
                                input = text
                                focused = true
                            }
                        } label: {
                            Label("Revert", systemImage: "arrow.uturn.backward")
                                .scaledFont(.caption2)
                        }
                        .buttonStyle(.plain)
                        .foregroundColor(.secondary)
                        .help("Remove this prompt and its reply — restore to input")
                        .disabled(assistantStore.isProcessing)
                    } else {
                        Button {
                            copyToClipboard(msg.content, id: msg.id)
                        } label: {
                            Label(copiedID == msg.id ? "Copied" : "Copy", systemImage: copiedID == msg.id ? "checkmark" : "doc.on.doc")
                                .scaledFont(.caption2)
                        }
                        .buttonStyle(.plain)
                        .foregroundColor(.secondary)
                        .help("Copy reply")
                        .disabled(msg.content.isEmpty || msg.isStreaming)
                    }
                }
                .padding(.horizontal, 4)
            }
            if !isUser { Spacer(minLength: 48) }
        }
        .frame(maxWidth: .infinity, alignment: isUser ? .trailing : .leading)
    }

    private func copyToClipboard(_ text: String, id: UUID) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        copiedID = id
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
            if copiedID == id { copiedID = nil }
        }
    }

    var inputBar: some View {
        HStack(spacing: 10) {
            TextField("Ask about the transcripts…", text: $input)
                .textFieldStyle(.plain)
                .scaledFontSize(15)
                .padding(.horizontal, 14)
                .padding(.vertical, 10)
                .background(
                    RoundedRectangle(cornerRadius: UIDesign.cornerCard, style: .continuous)
                        .fill(Color(nsColor: .textBackgroundColor))
                )
                .overlay(
                    RoundedRectangle(cornerRadius: UIDesign.cornerCard, style: .continuous)
                        .stroke(focused ? Color.accentColor.opacity(0.5) : Color.primary.opacity(0.12), lineWidth: 1)
                )
                .focused($focused)
                .onSubmit { send() }
                .disabled(assistantStore.isProcessing)

            Button { send() } label: {
                Image(systemName: "paperplane.fill")
                    .scaledFont(.callout)
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.regular)
            .tint(.accentColor)
            .clipShape(Circle())
            .disabled(input.trimmingCharacters(in: .whitespaces).isEmpty || assistantStore.isProcessing)
            .help("Send")

            if assistantStore.isProcessing {
                ProgressView()
                    .scaleEffect(0.8)
            }
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 14)
        .frame(maxWidth: 720)
        .frame(maxWidth: .infinity)
        // Blend with the card — no hairline; the card's own border is enough.
        .background(Color.clear)
    }

    func saveOwnFolders(_ list: [String]) {
        if let data = try? JSONEncoder().encode(list),
           let json = String(data: data, encoding: .utf8) {
            ownFoldersJSON = json
        }
    }

    func addFolder() {
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = true
        panel.message = "Select one or more project folders with transcripts and interview data"
        panel.prompt = "Add"
        guard panel.runModal() == .OK, !panel.urls.isEmpty else { return }
        var list = ownFolders
        for url in panel.urls where !list.contains(url.path) {
            list.append(url.path)
        }
        saveOwnFolders(list)
    }

    func removeFolder(at index: Int) {
        var list = ownFolders
        guard index < list.count else { return }
        list.remove(at: index)
        saveOwnFolders(list)
    }

    func loadOwnFolders() {
        let folders = ownFolders
        materialTrees = MaterialTree.scan(folders)
        guard !folders.isEmpty else {
            projectFolder = ""
            subStore.clearAll()
            docStore.reloadFolders([])
            return
        }
        projectFolder = folders[0]

        DispatchQueue.global().async {
            let fps = PythonBridge.detectFrameRate(in: folders[0])
            DispatchQueue.main.async {
                if let fps, fps != timelineFPS {
                    timelineFPS = fps
                }
                subStore.frameRate = timelineFPS
                subStore.loadFolders(folders)
                subStore.loadTranscriptsFolders(folders)
                docStore.reloadFolders(folders)
            }
        }
    }


    func rescanFolder() {
        let folders = ownFolders
        guard !folders.isEmpty else { return }
        knowledgeStore.invalidate()
        // Drop the knowledge cache file so nothing stale can be served
        if let first = folders.first {
            let name = URL(fileURLWithPath: first).lastPathComponent
            let caches = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
            try? FileManager.default.removeItem(at: caches.appendingPathComponent("assistanteditor_knowledge_\(name).json"))
        }
        docStore.reloadFolders(folders)
        subStore.loadFolders(folders, forceRebuild: true)
        subStore.loadTranscriptsFolders(folders, forceRebuild: true)
        buildKnowledge()
    }

    func buildKnowledge() {
        guard docStore.isLoaded || subStore.isLoaded else { return }
        if let data = projectThemesJSON.data(using: .utf8),
           let themes = try? JSONDecoder().decode([ProjectTheme].self, from: data) {
            knowledgeStore.dynamicThemes = themes
        }
        knowledgeStore.build(subStore: subStore, docStore: docStore)
    }

    func send() {
        let text = input
        input = ""
        focused = false
        assistantStore.send(text, knowledgeStore: knowledgeStore, subStore: subStore, docStore: docStore)
    }

    func saveConversation(thenClear: Bool = false) {
        guard !assistantStore.messages.isEmpty else { return }
        isGeneratingTitle = true
        assistantStore.generateConversationSynopsis { synopsis in
            DispatchQueue.main.async {
                isGeneratingTitle = false
                // Sanitize synopsis for filename; fallback to dated name
                let df = DateFormatter()
                df.dateFormat = "yyyy-MM-dd HHmm"
                let fallback = "conversation — \(df.string(from: Date()))"
                let rawTitle = (synopsis?.isEmpty == false ? synopsis! : fallback)
                let sanitized = rawTitle
                    .replacingOccurrences(of: "/", with: " – ")
                    .replacingOccurrences(of: ":", with: " – ")
                    .replacingOccurrences(of: "\"", with: "")
                    .replacingOccurrences(of: "'", with: "")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                let fileName = String(sanitized.prefix(60)).trimmingCharacters(in: .whitespaces) + ".html"

                let panel = NSSavePanel()
                panel.allowedContentTypes = [.html]
                panel.canCreateDirectories = true
                panel.nameFieldStringValue = fileName
                panel.title = "Save Conversation"
                panel.message = synopsis == nil ? "LLM title unavailable — using date." : "Title generated by \(selectedModel)"
                guard panel.runModal() == .OK, let url = panel.url else { return }
                let html = assistantStore.htmlExport(folders: ownFolders, synopsisTitle: synopsis)
                do {
                    try html.write(to: url, atomically: true, encoding: .utf8)
                    if thenClear { assistantStore.clear() }
                } catch {
                    NSSound.beep()
                }
            }
        }
    }
}
